///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/button.h>
#include <wx/frame.h>
#include <wx/gdicmn.h>
#include <wx/notebook.h>
#include <wx/scrolwin.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>

class MainFrame : public wxFrame
{
public:
    MainFrame() {}
    MainFrame(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = "COPA",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_FRAME_STYLE, const wxString &name = wxFrameNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "COPA",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_FRAME_STYLE, const wxString &name = wxFrameNameStr);

protected:

    // Class member variables

    wxButton* live_copy2;
    wxButton* live_copy;
    wxButton* live_delete2;
    wxButton* live_delete;
    wxButton* live_save2;
    wxButton* live_save;
    wxButton* m_btn;
    wxNotebook* m_notebook;
    wxScrolledWindow* m_scroll_panel;
    wxStaticText* m_static_text;
    wxTextCtrl* live_clipboard2;
    wxTextCtrl* live_clipboard;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
